title: Gabriel Cantanhede, M.Sc.
description: Meu CV online
url: https://gcantanhede-sci.github.io

# site settings
taglong: Senior Data Analyst, Pythonista
#tagshort: Sr Data Analyst, Py-man

# author settings
author:
  name: Gabriel Cantanhede
  email: g.l.cantanhede.silva@proton.me
photo: assets/files/photo.jpg
address: São Luis, MA, Brazil
#phone: +1 234 567 890

# social media links
social:
  github: gcantanhede-sci
  linkedin: gabriel-l-cantanhede-da-silva

# build settings
permalink: pretty

exclude:
  - docker-compose.yml
  - Gemfile
  - LICENSE
  - README.md
  - vendor/
  - cv.aux
  - cv.fdb_latexmk
  - cv.fls
  - cv.log
  - cv.out
  - cv.synctex.gz
  - cv.tex

plugins:
  - jekyll-seo-tag
  - jekyll-sitemap