title: Gabriel Cantanhede, M.Sc.
description: Meu CV online
baseurl: ""
url: https://gcantanhede-sci.github.io

theme: cvless

# site settings
taglong: Analista de Dados SR, Pythonista
#tagshort: Sr Data Analyst, Py-man

# author settings
author:
  name: Gabriel Cantanhede
  email: g.l.cantanhede.silva@proton.me
photo: assets/files/photo.jpg
address: São Luis, MA, Brazil
#phone: +1 234 567 890

# social media links
social:
  github: gcantanhede-sci
  linkedin: gabriel-l-cantanhede-da-silva

# build settings
permalink: pretty
exclude:
  - docker-compose.yml
  - LICENSE
  - README.md
  [vendor]
